Poke_inventory/authentication/routes.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from Poke_inventory.models import User, db, check_password_hash
from Poke_inventory.forms import UserLoginForm

# Import from flask login
from flask_login import login_user, logout_user, current_user, login_required

auth = Blueprint('auth', __name__, template_folder = 'auth_templates')

@auth.route('/signup', methods = ['GET', 'POST'])
def signup():
    form = UserLoginForm()
    try:
        if request.method == "POST" and form.validate_on_submit():
            email = form.email.data
            password = form.password.data
            print(email, password)

            user = User(email, password)

            db.session.add(user)
            db.session.commit()

            flash(f"You have succesfully created a user account {email}", 'user-created')

            return redirect(url_for('auth.signin'))
    except:
        raise Exception('Invalid Form Data: Please Check Your Form')   

    
    return render_template('signup.html', form=form)

@auth.route('/signin', methods = ['GET', 'POST'])
def signin():
    form = UserLoginForm()

    try:
        if request.method == "POST" and form.validate_on_submit():
            email = form.email.data
            password = form.password.data
            print(email, password)

            logged_user = User.query.filter(User.email == email).first()
            if logged_user and check_password_hash(logged_user.password, password):
                login_user(logged_user)
                flash('You were succesfully login in!', 'auth-success')
                return redirect(url_for('site.profile'))
            else:
                flash('Your Email/Password is incorrect', 'auth-failed')
                return redirect(url_for('auth.signin'))
    except:
        raise Exception('Invalid Form Data: Please Check Your Form')

    return render_template('signin.html', form=form)

@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('site.home'))

Poke_inventory/site/routes.py
from flask import Blueprint, render_template
from flask_login.utils import login_required

site = Blueprint('site', __name__, template_folder = 'site_templates')

@site.route('/')
def home():
    return render_template('index.html')

@site.route('/profile')
@login_required
def profile():
    return render_template('profile.html')   

@site.route('/addtoteam')
@login_required
def addtoteam():
    return render_template('addtoteam.html')

Poke_inventory/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>

<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<meta name="Description" content="Enter your description here"/>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.1.0/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
<link rel="stylesheet" href="../static/css/main.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
 
<title>Poké Inventory API</title>
</head>
<body>
    <!--Navbar Here-->
    <nav class="ct-nav">
        <div>
            <img src="../static/images/PokeLogo1.png" alt="PokeLogo">
        </div>
        <!--Nav Items Here-->
        <div>
            <ul id="horizontal-list">
                <a href="{{ url_for ('site.home') }}">
                    <li>Poké Inventory Home</li>
                </a>
                <a href="#">
                    <li>Donate</li>
                </a>
                <a href="{{ url_for('site.profile') }}">
                    <li>Profile</li>
                </a>
                <a href="{{ url_for('site.addtoteam') }}">
                    <li>Add to Party</li>
                </a>
                {% if current_user.is_authenticated %}
                <a href="{{ url_for('auth.logout') }}">
                    <li>Log Out</li>
                </a>
                {% else %}
                
                </a>
                <a href="{{ url_for('auth.signin') }}">
                    <li>Sign In</li>
                </a>
                <a href="{{ url_for('auth.signup') }}">
                    <li>Sign Up</li>
                </a>
                {% endif %}
            </ul>
        </div>
    </nav>
<!--End of Navbar-->

    {% block content %}


    {% endblock content %}

<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.9.2/umd/popper.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.1.0/js/bootstrap.min.js"></script>
</body>
</html>

Poke_inventory/templates/forms.html
<!--HTML produced by the Flask Form-->
<form method = "POST">
    {{ form.hidden_tag() }}
    <div class = "form-group">
        <fieldset id="email-field">
            {{ form.email.label }}
            {{ form.email(class="form-control", placeholder = "Example@example.com")}}
        </fieldset>

        <fieldset id="idpass-field">
            {{ form.password.label }}
            {{ form.password(class = "form-control", placeholder = "Enter password here!") }}
        </fieldset>
        
        <!--Submit Button-->
        <div class="submit-button">
        {{ form.submit_button(class="btn btn-danger btn-block") }}
        </div>
    </div>
</form>